#!/usr/bin/env python3
"""Regenerate projects/REGISTRY.md from every projects/*/PROJECT.md.

Usage: build_registry.py TARGET_DIR [--check]
--check: exit 1 if the existing REGISTRY.md differs from what would be generated.
"""
import argparse
import sys
from pathlib import Path

from common import find_root, TIERS, TODAY, load_projects

ORDER = {t: i for i, t in enumerate(TIERS)}


def render(root: Path) -> str:
    rows = load_projects(root)
    rows.sort(key=lambda r: (ORDER.get(r.get("tier"), 9), r.get("name", r["slug"]).lower()))
    out = ["# Project registry", "",
           "Generated by build_registry.py; do not edit by hand. Find the slug, then load `projects/<slug>/PROJECT.md`. "
           "Build only against status `live`.", "",
           f"{len(rows)} projects. Regenerated {TODAY}.", "",
           "| Slug | Name | Tier | Voice | Status | Owner |", "|---|---|---|---|---|---|"]
    for r in rows:
        out.append(f"| `{r['slug']}` | {r.get('name','')} | {r.get('tier','')} | {r.get('voice','')} | {r.get('status','')} | {r.get('owner','')} |")
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("target", nargs="?", default=None, help="brand system root; default: found from the current directory")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    root = Path(a.target).expanduser().resolve() if a.target else find_root()
    reg = root / "projects" / "REGISTRY.md"
    text = render(root)
    if a.check:
        current = reg.read_text() if reg.exists() else ""
        # ignore the regenerated-date line when comparing
        strip = lambda s: "\n".join(l for l in s.splitlines() if not l.startswith(("Regenerated", f"{len(load_projects(root))} projects")))
        if strip(current) != strip(text):
            print("REGISTRY.md is stale; run build_registry.py")
            return 1
        print("REGISTRY.md is current")
        return 0
    reg.parent.mkdir(parents=True, exist_ok=True)
    reg.write_text(text)
    print(f"wrote {reg} ({len(load_projects(root))} projects)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
